/*
 * ___FILENAME___
 * ___PACKAGENAME___
 *
 * Created by ___FULLUSERNAME___ on ___DATE___.
 * Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
 *
 */

#ifndef _GUARD_PROJECT___PROJECTNAMEASIDENTIFIER____FILE___FILEBASENAMEASIDENTIFIER____
#define _GUARD_PROJECT___PROJECTNAMEASIDENTIFIER____FILE___FILEBASENAMEASIDENTIFIER____


#define MENU_BAR 1

#define APPLE_MENU 3
#define FILE_MENU 4
#define EDIT_MENU 5

#define EDIT_UNDO 250
#define EDIT_CUT 251
#define EDIT_COPY 252
#define EDIT_PASTE 253
#define EDIT_CLEAR 254

#define FILE_NEW 401
#define FILE_OPEN 402
#define FILE_CLOSE 255
#define FILE_QUIT 256

#define APPLE_ABOUT 301

#define ABOUT_ALERT_STRING 1

#define WINDOW_RESID 1001

#define TOOL_STARTUP 1


#endif /* defined(_GUARD_PROJECT___PROJECTNAMEASIDENTIFIER____FILE___FILEBASENAMEASIDENTIFIER____) */
