#!/bin/bash

for item in ~/"Library/Developer/Xcode/Templates/Apple IIgs" ~/"Library/Developer/Xcode/Templates/File Templates/Apple IIgs"
do
    if [ -d "$item" ]
    then
        rm -rf "$item"
    fi
done
