#!/bin/bash

rm -rf "$HOME/Library/Developer/Xcode/Templates/Apple IIgs"
rm -rf "$HOME/Library/Developer/Xcode/Templates/File Templates/Apple IIgs"
rm -rf "$HOME/Library/Developer/Xcode/Templates/File Templates/Apple II/Merlin Assembly File.xctemplate"
rm -rf "$HOME/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin"

