#!/bin/bash

TMPDIR=/tmp/pkg.$$

mkdir $TMPDIR
cp -R pkg/Templates $TMPDIR
cp -R pkg/Specifications $TMPDIR
cp -R pkg/Plug-ins $TMPDIR

PROJECTS=/tmp/projects.$$
cat > $PROJECTS << EOF
cda:orca:C Classic Desk Accessory
cdev:orca:C Control Panel
desktop:orca:C Desktop Application
shell:gno:C GNO Shell Command
nda:orca:C New Desk Accessory
shell:orca:C ORCA Shell Command
shell:orca:Asm ORCA Shell Command
EOF

while read PROJECT
do
    PROJECTTYPE=`echo $PROJECT | awk -F: '{print $1}'`
    SHELLTYPE=`echo $PROJECT | awk -F: '{print $2}'`
    PROJECTNAME=`echo $PROJECT | awk -F: '{print $3}'`
    sed "
        /^# TARGETTYPE=${PROJECTTYPE}/s/^# //
        /^# export ORCA=.*\/${SHELLTYPE}$/s/^# //" Makefile > "${TMPDIR}/Templates/Apple IIgs/${PROJECTNAME}.xctemplate/Makefile"
    cp -R make "${TMPDIR}/Templates/Apple IIgs/${PROJECTNAME}.xctemplate/"
done < $PROJECTS

rm -f $PROJECTS

pkgbuild --root $TMPDIR --version 0.1 --identifier com.halcyontouch.Apple2gsTemplate.pkg --install-location /Library/Developer/Xcode/ --scripts pkg/scripts/ Apple2GSXcodeTemplate.pkg
productbuild --distribution pkg/Distribution.xml --resource ./pkg temp.pkg
rm Apple2GSXcodeTemplate.pkg
#productsign --sign "Developer ID Installer: Halcyon Touch Software" temp.pkg Apple2GSXcodeTemplate.pkg
cp temp.pkg Apple2GSXcodeTemplate.pkg
rm temp.pkg

#rm -rf $TMPDIR
