#!/bin/bash

TMPDIR=/tmp/pkg.$$

cp -R pkg/Templates $TMPDIR

for PROJECT in "Apple IIgs C Shell Command" "Apple IIgs Asm Shell Command"
do
    echo cp -R Makefile make "${TMPDIR}/Apple IIgs/${PROJECT}.xctemplate/"
    cp -R Makefile make "${TMPDIR}/Apple IIgs/${PROJECT}.xctemplate/"
done

pkgbuild --root $TMPDIR --version 0.1 --identifier com.halcyontouch.Apple2gsTemplate.pkg --install-location /Library/Developer/Xcode/Templates/ --scripts pkg/scripts/ Apple2GSXcodeTemplate.pkg
productbuild --distribution pkg/Distribution.xml --resource ./pkg temp.pkg
rm Apple2GSXcodeTemplate.pkg
#productsign --sign "Developer ID Installer: Halcyon Touch Software" temp.pkg Apple2GSXcodeTemplate.pkg
cp temp.pkg Apple2GSXcodeTemplate.pkg
rm temp.pkg

rm -rf $TMPDIR
